/// Flutter icons MyLogo
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyLogo
///      fonts:
///       - asset: fonts/MyLogo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyLogo {
  MyLogo._();

  static const _kFontFam = 'MyLogo';

  static const IconData cat = const IconData(0xe800, fontFamily: _kFontFam);
}
